import { Component, Input, OnInit, ViewChild } from "@angular/core";

import { CommonModule } from "@angular/common";
import {
  ActivatedRoute,
  ActivatedRouteSnapshot,
  Router,
  RouterModule,
} from "@angular/router";
import { ReactiveFormsModule } from "@angular/forms";

import { PaymentService } from "src/app/services/payment.service";

import { environment } from "src/environments/environment";
import { MemberService } from "src/app/services/member.service";

import { v4 as uuidv4 } from "uuid";
import { CommonService } from "src/app/services/common.service";
import { NgbModal } from "@ng-bootstrap/ng-bootstrap";

import { PyamentDetilModalComponent } from "./pyament-detil-modal/pyament-detil-modal.component";
import {
  IMembersGetDto,
  MoodleUpdateDto,
} from "src/app/models/auth/membersDto";
import { errorToast, successToast, infoToast } from "src/app/services/toast.service";

@Component({
  selector: "app-payment-verfication",
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule],
  templateUrl: "./payment-verfication.component.html",
  styleUrls: ["./payment-verfication.component.scss"],
})
export default class PaymentVerficationComponent implements OnInit {
  txt_rn: string;
  baseUrl = environment.clienUrl;
  autoGeneratedId: string;
  selectedMember!: IMembersGetDto;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private paymentService: PaymentService,
    private commonService: CommonService,
    private memberService: MemberService,
    private modalService: NgbModal
  ) {}

  ngOnInit(): void {
    const snapshot: ActivatedRouteSnapshot = this.route.snapshot;
    this.txt_rn = snapshot.paramMap.get("txt_rn");

    if (this.txt_rn) {
      this.verifyPayment();
    } else {
      errorToast("Invalid payment reference", "No transaction reference found in the URL.");
    }
    
    this.autoGeneratedId = uuidv4();
  }

  verifyPayment() {
    // this.paymentService.verifyPayment(this.txt_rn).subscribe({
    //   next: (res) => {
    //     if (res.response) {
    //       if (res.response.data.status == "success") {
    //         this.MakePaymentConfirmation();
    //       } else {
    //         errorToast("Payment verification failed", res.response.data.status || res.message);
    //       }
    //     } else {
    //         errorToast("Payment verification failed", res.response.status || res.message);
    //     }
    //   },
    //   error: (err) => {
    //     errorToast("Verification error", err.message || "Failed to verify payment");
    //   },
    // });
    
    // For now, directly call payment confirmation
    this.MakePaymentConfirmation();
  }

  MakePaymentConfirmation() {
    this.paymentService.MakePaymentConfirmation(this.txt_rn).subscribe({
      next: (res) => {
        if (res.success) {
          successToast("Your payment was successful!");
          this.selectedMember = res.data;
          
          // Show success message and then open details modal
          setTimeout(() => {
            this.openModal();
          }, 1000);
        } else {
          errorToast("Payment confirmation failed", res.message || "Unable to confirm payment");
        }
      },
      error: (err) => {
        errorToast("Payment confirmation error", err.message || "Failed to confirm payment");
      }
    });
  }

  updateMember(updateMoodleDto: MoodleUpdateDto) {
    this.memberService.updateMoodleApi(updateMoodleDto).subscribe({
      next: (res) => {
        if (res.success) {
          successToast("Member updated successfully!");
          this.openModal();
        } else {
          errorToast("Member update failed", res.message || "Unable to update member");
          this.openModal(); // Still show modal for user to see details
        }
      },
      error: (err) => {
        errorToast("Member update error", err.message || "Failed to update member");
        this.openModal(); // Still show modal for user to see details
      },
    });
  }

  openModal() {
    let modalRef = this.modalService.open(PyamentDetilModalComponent, {
      size: "lg",
      backdrop: 'static'
    });

    modalRef.componentInstance.userId = this.selectedMember.id;
    modalRef.componentInstance.fullName = this.selectedMember.fullName;
    modalRef.componentInstance.membershipId = this.selectedMember.memberId;
    modalRef.componentInstance.membershipType = this.selectedMember.membershipTypeName;

    modalRef.result.then(() => {
      window.location.href = this.baseUrl + "/auth/membership-login/" + this.selectedMember.memberId;
    }).catch(() => {
      // Modal was dismissed, redirect anyway
      window.location.href = this.baseUrl + "/auth/membership-login/" + this.selectedMember.memberId;
    });
  }
}
